compile-bytecode = true
native-tls = true
python-downloads = "manual"
python-preference = "managed"

[pip]
emit-build-options = true
emit-index-annotation = true
emit-index-url = true
generate-hashes = true
