" GUI
set guioptions-=m
set guioptions-=T
set guioptions-=r
set guioptions-=R
set guioptions-=l
set guioptions-=L
set guioptions-=b
set guioptions+=d
set guioptions+=a
set guioptions+=P
set guifont=JetBrains\ Mono\ Nerd\ Font\ Mono\ 10
