" Core settings
set nocp
filetype plugin on
set autoindent
set autowrite
set textwidth=120
set showmode
set tabstop=2
set softtabstop=2
set shiftwidth=2 
set smartindent
set smarttab
syntax on 
filetype plugin indent on
set pastetoggle=<F2>
set expandtab
set nobackup 
set noswapfile 
set nowritebackup
set icon
set hlsearch
set incsearch
set hidden
set history=100
set ttyfast
set wildmenu
let mapleader = ","
nnoremap <up> <C-a>
nnoremap <down> <C-x>
noremap <C-n> <C-d>
noremap <C-p> <C-b>
set guioptions-=m
set guioptions-=T
set guioptions-=r
set guioptions-=R
set guioptions-=l
set guioptions-=L
set guioptions-=b
set guioptions+=d
set guioptions+=a

colorscheme habamax
set guifont=JetBrains\ Mono\ Nerd\ Font\ Mono\ 10
