local opt = vim.opt
local cmd = vim.cmd

opt.number = true
opt.showmode = true
opt.tabstop = 2
opt.softtabstop = 2
opt.shiftwidth = 2
opt.smartindent = true
opt.smarttab = true
opt.expandtab = true
opt.swf = false
opt.wb = false
opt.icon = true
opt.history = 1000
opt.clipboard = 'unnamedplus'
opt.termguicolors = true
vim.g.mapleader = ','
opt.mouse = 'a'
opt.laststatus = 2
